name: azure-mysql
pipeline:
  - name: parsed_event
    external:
      name: json.parse-json
      properties:
        input_field: original.message
        output_field: message
  - name: set_ecs_fields

stages:
  set_ecs_fields:
    actions:
      - set:
          action.name: "{{parsed_event.message.properties.event_subclass}}"
          action.outcome: "success"
          action.type: "{{parsed_event.message.properties.event_class}}"
          group.name: "{{parsed_event.message.ResourceGroup}}"
          host.hostname: "{{parsed_event.message.LogicalServerName}}"
          log.hostname: "{{parsed_event.message.LogicalServerName}}"
          source.ip: "{{parsed_event.message.properties.ip}}"
          user.name: "{{parsed_event.message.properties.user}}"
