repos:
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.31.0
    hooks:
      - id: yamllint
        args: ['-d', '{extends: relaxed, rules: {line-length: {max: 199}}}', '--no-warnings']
  - repo: https://github.com/google/yamlfmt
    rev: v0.8.0
    hooks:
      - id: yamlfmt
