name: vulnerability_assessment_scanner
pipeline:
  - name: parsed_event
    external:
      name: json.parse-json
      properties:
        input_field: "{{original.message}}"
        output_field: message

  - name: set_common_fields

stages:
  set_common_fields:
    actions:
      - set:
          "@timestamp": "{{parsed_event.message.created_at}}"

          event.kind: "event"
          event.category: ["vulnerability"]
          event.type: ["info"]
          event.dataset: "issue"
          event.action: "{{parsed_event.message.trigger.type}}"

          observer.vendor: "SecurityScorecard"
          observer.product: "Vulnerability Assessment Scanner"

          cloud.account.name: "{{parsed_event.message.domain}}"
          organization.name: "{{parsed_event.message.trigger.breach.company_name}}"

          scorecard.id: "{{parsed_event.message.scorecard_id}}"
          scorecard.selected: "{{parsed_event.message.trigger.selected}}"
          scorecard.severity: "{{parsed_event.message.trigger.severity}}"

      - set:
          event.kind: "alert"
          event.dataset: "breach"
          event.reason: "{{parsed_event.message.trigger.breach.description}}"
          scorecard.breach.root_cause: "{{parsed_event.message.trigger.breach.root_cause}}"
        filter: "{{parsed_event.message.trigger.type == 'breach_reported'}}"
