name: ocsf
pipeline:
  - name: parse_event
    external:
      name: json.parse-json
      properties:
        input_field: "{{original.message}}"
        output_field: message

  - name: parse_date_end_time_dt
    external:
      name: date.parse
      properties:
        input_field: '{{ parse_event.message.end_time_dt }}'
        output_field: datetime
    filter: '{{ parse_event.message.end_time_dt != None and parse_event.message.end_time_dt != '''' }}'

  - name: parse_date_end_time
    external:
      name: date.parse
      properties:
        input_field: '{{ parse_event.message.end_time }}'
        output_field: datetime
    filter: '{{ parse_event.message.end_time != None and parse_event.message.end_time != '''' }}'

  - name: parse_date_timestamp_from_time_dt
    external:
      name: date.parse
      properties:
        input_field: '{{ parse_event.message.time_dt }}'
        output_field: datetime
      filter: '{{ parse_event.message.time_dt != None and parse_event.message.time_dt != '''' }}'

  - name: parse_date_timestamp_from_time
    external:
      name: date.parse
      properties:
        input_field: '{{ parse_event.message.time }}'
        output_field: datetime
    filter: '{{ parse_event.message.time != None and parse_event.message.time != '''' }}'

  - name: parse_date_time_dt
    external:
      name: date.parse
      properties:
        input_field: '{{ parse_event.message.time_dt }}'
        output_field: datetime
    filter: '{{ parse_event.message.time_dt != None and parse_event.message.time_dt != '''' }}'

  - name: parse_date_time
    external:
      name: date.parse
      properties:
        input_field: '{{ parse_event.message.time }}'
        output_field: datetime
    filter: '{{ parse_event.message.time != None and parse_event.message.time != '''' }}'

  - name: parse_date_metadata_logged_time_dt
    external:
      name: date.parse
      properties:
        input_field: '{{ parse_event.message.metadata.logged_time_dt }}'
        output_field: datetime
    filter: '{{ parse_event.message.metadata.logged_time_dt != None and parse_event.message.metadata.logged_time_dt != '''' }}'

  - name: parse_date_metadata_logged_time
    external:
      name: date.parse
      properties:
        input_field: '{{ parse_event.message.metadata.logged_time }}'
        output_field: datetime
    filter: '{{ parse_event.message.metadata.logged_time != None and parse_event.message.metadata.logged_time != '''' }}'

  - name: parse_date_metadata_modified_time_dt
    external:
      name: date.parse
      properties:
        input_field: '{{ parse_event.message.metadata.modified_time_dt }}'
        output_field: datetime
    filter: '{{ parse_event.message.metadata.modified_time_dt != None and parse_event.message.metadata.modified_time_dt != '''' }}'

  - name: parse_date_metadata_modified_time
    external:
      name: date.parse
      properties:
        input_field: '{{ parse_event.message.metadata.modified_time }}'
        output_field: datetime
    filter: '{{ parse_event.message.metadata.modified_time != None and parse_event.message.metadata.modified_time != '''' }}'

  - name: parse_date_metadata_processed_time_dt
    external:
      name: date.parse
      properties:
        input_field: '{{ parse_event.message.metadata.processed_time_dt }}'
        output_field: datetime
    filter: '{{ parse_event.message.metadata.processed_time_dt != None and parse_event.message.metadata.processed_time_dt != '''' }}'

  - name: parse_date_metadata_processed_time
    external:
      name: date.parse
      properties:
        input_field: '{{ parse_event.message.metadata.processed_time }}'
        output_field: datetime
    filter: '{{ parse_event.message.metadata.processed_time != None and parse_event.message.metadata.processed_time != '''' }}'

  - name: parse_date_start_time_dt
    external:
      name: date.parse
      properties:
        input_field: '{{ parse_event.message.start_time_dt }}'
        output_field: datetime
    filter: '{{ parse_event.message.start_time_dt != None and parse_event.message.start_time_dt != '''' }}'

  - name: parse_date_start_time
    external:
      name: date.parse
      properties:
        input_field: '{{ parse_event.message.start_time }}'
        output_field: datetime
    filter: '{{ parse_event.message.start_time != None and parse_event.message.start_time != '''' }}'

  - name: set_event_kind
  - name: set_event_category
  - name: set_event_type
  - name: set_common_fields
  - name: set_fields

stages:
  set_event_kind:
    actions:
      - set:
          event.kind: "event"
        filter: "{{parse_event.message.class_uid in [1001,1002,1003,1004,1005,1006,1007,3001,3002,3003,3005,3006,4001,4002,4003,4004,4005,4006,4007,4008,4009,4010,4011,4012,5001,5002,6001,6002,6003,6004]}}"

      - set:
          event.kind: "alert"
        filter: "{{parse_event.message.class_uid == 2001}}"

  set_event_category:
    actions:
      - set:
          event.category: ["malware"]
        filter: "{{parse_event.message.class_uid == 2001 and parse_event.message.malware != null}}"

      - set:
          event.category: [ "vulnerability" ]
        filter: "{{parse_event.message.class_uid == 2001 and parse_event.message.vulnerabilities != null}}"

      - set:
          event.category: [ "iam" ]
        filter: "{{parse_event.message.class_uid in [3001, 3005, 3006]}}"

      - set:
          event.category: [ "authentication" ]
        filter: "{{parse_event.message.class_uid == 3002}}"

      - set:
          event.category: [ "session" ]
        filter: "{{parse_event.message.class_uid == 3003}}"

      - set:
          event.category: [ "network" ]
        filter: "{{parse_event.message.class_uid in [4001, 4003, 4004, 4005, 4007, 4008, 4010]}}"

      - set:
          event.category: [ "api" ]
        filter: "{{parse_event.message.class_uid in [4002, 4006]}}"

      - set:
          event.category: [ "file" ]
        filter: "{{parse_event.message.class_uid in [1001, 4006, 4008, 4010, 4011]}}"

      - set:
          event.category: [ "email" ]
        filter: "{{parse_event.message.class_uid in [4009, 4011, 4012]}}"

      - set:
          event.category: [ "web" ]
        filter: "{{parse_event.message.class_uid in [6003, 6004]}}"

      - set:
          event.category: [ "package" ]
        filter: "{{parse_event.message.class_uid == 6002}}"

      - set:
          event.category: [ "configuration" ]
        filter: "{{parse_event.message.class_uid == 5002}}"

      - set:
          event.category: [ "driver" ]
        filter: "{{parse_event.message.class_uid in [1002, 1003]}}"

      - set:
          event.category: [ "process" ]
        filter: "{{parse_event.message.class_uid == 1007}}"

  set_event_type:
    actions:
      - set:
          event.type: ["info"]
        filter: "{{parse_event.message.class_uid in [1001,1002,1003,1007,2001,3001,3002,3003,3005,3006,4001,4002,4003,4004,4005,4006,4007,4008,4009,4010,4011,4012,5001,5002,6002,6003,6004]}}"

      - set:                                               
          event.type: ["user"]
        filter: "{{parse_event.message.class_uid in [3001, 3006]}}"
        
      - set:                                               
          event.type: ["group"]
        filter: "{{parse_event.message.class_uid in [3005]}}"
        
      - set:                                               
          event.type: ["protocol"]                                   
        filter: "{{parse_event.message.class_uid in [4003,4004,4005,4007,4008]}}"  
        
      - set:                                               
          event.type: ["creation"]
        filter: "{{parse_event.message.class_uid in [1001,3001,4006,5002] and parse_event.message.activity_name in ['Create','File Create','Log']}}"
        
      - set:                                               
          event.type: ["access"]
        filter: "{{parse_event.message.class_uid in [1001,4006,4010,5002,6004] and parse_event.message.activity_name in ['Read','File Open','Preview','Open','Access Grant','Access Deny','Access Revoke','Access Error','Log']}}"
        
      - set:                                               
          event.type: ["deletion"]
        filter: "{{parse_event.message.class_uid in [1001,3001,4010,6002] and parse_event.message.activity_name in ['Delete','Remove']}}"
        
      - set:                                               
          event.type: ["start"]                                   
        filter: "{{parse_event.message.class_uid in [1007,3002,4001,4007,6002] and parse_event.message.activity_name in ['Launch','Logon','Open','Start']}}"
        
      - set:                                               
          event.type: ["end"]
        filter: "{{parse_event.message.class_uid in [1007,3002,4001,4007,6002] and parse_event.message.activity_name in ['Terminate','Logoff','Close','Stop']}}"
        
      - set:                                               
          event.type: ["denied"]
        filter: "{{parse_event.message.class_uid in [4001, 4003, 4004, 4007] and parse_event.message.activity_name in ['Refuse','Decline']}}"

      - set:                                               
          event.type: ["allowed"]
        filter: "{{parse_event.message.class_uid in [4004] and parse_event.message.activity_name in ['Ack']}}"
        
      - set:                                               
          event.type: ["change"]
        filter: "{{parse_event.message.class_uid in [1001, 4006, 4010] and parse_event.message.activity_name in ['Update','File Supersede','File Overwrite','Update','Rename']}}"
        
      - set:                                               
          event.type: ["connection"]
        filter: "{{parse_event.message.class_uid in [4005] and parse_event.message.activity_name in ['Connect Request','Connect Response']}}"
        
      - set:                                               
          event.type: ["installation"]
        filter: "{{parse_event.message.class_uid in [6002] and parse_event.message.activity_name in ['Install']}}"
        
      - set:                                               
          event.type: ["error"]
        filter: "{{parse_event.message.class_uid in [6004] and parse_event.message.activity_name in ['Access Error']}}"

  set_common_fields:
    actions:
      - set:
          cloud.account.id: "{{parse_event.message.cloud.account.uid}}"
          cloud.account.name: "{{parse_event.message.cloud.account.name}}"
          cloud.availability_zone: "{{parse_event.message.cloud.zone}}"
          cloud.project.id: "{{parse_event.message.cloud.project_uid}}"
          cloud.provider: "{{parse_event.message.cloud.provider}}"
          cloud.region: "{{parse_event.message.cloud.region}}"

          event.action: "{{parse_event.message.activity_name.lower().replace(': ', '-')}}"
          event.code: "{{parse_event.message.metadata.event_code}}"
          event.duration: "{{parse_event.message.duration * 1_000_000}}" # in nanoseconds
          # event.id: "{{parse_event.message.metadata.uid}}"  # @todo we can't assign this. use custom field?
          event.provider: "{{parse_event.message.metadata.log_provider}}"
          event.sequence: "{{parse_event.message.metadata.sequence}}"

          event.severity: "{{parse_event.message.severity_id}}"

      - set:
          event.provider: "{{parse_event.message.metadata.product.vendor_name}}"
        filter: "{{parse_event.message.metadata.log_provider == None}}"

      - set:
          event.end: "{{parse_date_end_time_dt.datetime}}"
        filter: "{{parse_date_end_time_dt.datetime != None}}"

      - set:
          event.end: "{{parse_date_end_time.datetime}}"
        filter: "{{parse_date_end_time.datetime != None}}"

      - set:
          event.start: "{{parse_date_start_time_dt.datetime}}"
        filter: "{{parse_date_start_time_dt.datetime != None}}"

      - set:
          event.start: "{{parse_date_start_time.datetime}}"
        filter: "{{parse_date_start_time.datetime != None}}"

      - translate:
        dictionary:
          0: "unknown"
          1: "success"
          2: "failure"
        mapping:
          parse_event.message.status_id: event.outcome

  set_fields:
    actions:
      - set:
          #"@timestamp": "{{parse_event.message.time | to_rfc3339}}"

          ocsf: "{{parse_event.message}}"
          #process: "{{parse_event.message.process}}"
