name: ocsf
pipeline:
  - name: parse_message
    external:
      name: json.parse-json
      properties:
        input_field: '{{original.message}}'
        output_field: message

  - name: set_fields

stages:
  set_fields:
    actions:
      - set:
          "@timestamp": "{{parse_message.message.time | to_rfc3339}}"

          ocsf: "{{parse_message.message}}"
          process: "{{parse_message.message.process}}"
