name: azure-ad
pipeline:
  - name: parsed_event
    external:
      name: json.parse-json
  - name: azuread
  - name: log_type_authentication
    filter: "{{parsed_event.message.authenticationDetails != null}}"
  - name: log_type_auditlogs
    filter: '{{ parsed_event.message.properties != null and parsed_event.message.category == "AuditLogs" }}'
  - name: log_type_auditlogs_has_message_properties
    filter: '{{ parsed_event.message.properties != null and parsed_event.message.category == "AuditLogs" }}'
  - name: read_message_properties
    filter: '{{ parsed_event.message.properties != null }}'
  - name: read_message_properties_location_geoCoordinates
    filter: '{{ parsed_event.message.properties != null and parsed_event.message.properties.location != null}}'
  - name: read_device_details
    filter: '{{ parsed_event.message.deviceDetail != null }}'


stages:
  read_device_details:
    actions:
      - set:
          host.os.name: '{{ parsed_event.message.deviceDetail.operatingSystem }}'
          user_agent.name: '{{ parsed_event.message.deviceDetail.browser }}'

  read_message_properties:
    actions:
      - set:
          action.outcome: '{{parsed_event.message.properties.result}}'
          action.type: "{{parsed_event.message.properties.operationType |lower}}"
          event.reason: '{{ parsed_event.message.properties.riskType }}'
          client.user.full_name: '{{ parsed_event.message.properties.userDisplayName }}'
          client.user.email: '{{ parsed_event.message.properties.userPrincipalName }}'
          user_agent.original: '{{ parsed_event.message.properties.userAgent }}'
          service.name: '{{ parsed_event.message.properties.resourceDisplayName }}'

      - set:
          event.type: [ "connection" ]
        filter: '{{ parsed_event.message.properties.activity == "signin" }}'
      - set:
          event.reason: '{{parsed_event.message.properties.status.failureReason}}'
        filter: '{{ parsed_event.message.properties.status != null }}'
      - set:
          event.category: ["iam", "change"]
        filter: '{{ parsed_event.message.properties.category == "DirectoryManagement" or parsed_event.message.properties.category == "AuditLogs" }}'

  read_message_properties_location_geoCoordinates:
    actions:
      - set:
          client.geo.city_name: "{{ parsed_event.message.properties.location.city}}"
          client.geo.region_name: "{{ parsed_event.message.properties.location.state }}"
          client.geo.country_iso_code: "{{ parsed_event.message.location}}"

      - set:
          client.geo.location: '{ "lon": "{{parsed_event.message.properties.location.geoCoordinates.longitude}}","lat": "{{parsed_event.message.properties.location.geoCoordinates.latitude}}" }'
        filter: '{{ parsed_event.message.properties.location.geoCoordinates != null and parsed_event.message.properties.location.geoCoordinates.longitude != "" and parsed_event.message.properties.location.geoCoordinates.latitude != "" }}'

  azuread:
    actions:
      - set:
          service.type: "ldap"
          service.name: '{{ parsed_event.message.resourceDisplayName or "Azure Active Directory"}}'
          log.hostname: "azureactivedirectory"
          host.hostname: "azureactivedirectory"
          action.name: '{{parsed_event.message.operationName}}'
          user.id: '{{ parsed_event.message.userId}}'
          user.name: '{{ parsed_event.message.userPrincipalName}}'
          client.ip: '{{parsed_event.message.ipAddress}}'
          user_agent.original: '{{ parsed_event.message.userAgent }}'

      - set:
          azuread.resourceId: '{{parsed_event.message.resourceId}}'
          azuread.operationName: '{{parsed_event.message.operationName}}'
          azuread.operationVersion: '{{parsed_event.message.operationVersion}}'
          azuread.category: '{{parsed_event.message.category}}'
          azuread.tenantId: '{{parsed_event.message.tenantId}}'
          azuread.resultSignature: '{{parsed_event.message.resultSignature}}'
          azuread.durationMs: '{{parsed_event.message.durationMs}}'
          azuread.correlationId: '{{parsed_event.message.correlationId}}'
          azuread.identity: '{{parsed_event.message.identity}}'
          azuread.Level: '{{parsed_event.message.Level}}'
          azuread.location: '{{parsed_event.message.location}}'

      - set:
          azuread.properties.id: '{{parsed_event.message.properties.id}}'
          azuread.properties.requestId: '{{parsed_event.message.properties.requestId}}'
          azuread.properties.correlationId: '{{parsed_event.message.properties.correlationId}}'
          azuread.properties.riskEventType: '{{parsed_event.message.properties.riskEventType}}'
          azuread.properties.riskState: '{{parsed_event.message.properties.riskState}}'
          azuread.properties.riskLevel: '{{parsed_event.message.properties.riskLevel}}'
          azuread.properties.riskDetail: '{{parsed_event.message.properties.riskDetail}}'
          azuread.properties.source: '{{parsed_event.message.properties.source}}'
          azuread.properties.detectionTimingType: '{{parsed_event.message.properties.detectionTimingType}}'
          azuread.properties.activity: '{{parsed_event.message.properties.activity}}'
          azuread.properties.activityDateTime: '{{parsed_event.message.activityDateTime}}'
          azuread.properties.detectedDateTime: '{{parsed_event.message.detectedDateTime}}'
          azuread.properties.lastUpdatedDateTime: '{{parsed_event.message.lastUpdatedDateTime}}'
          azuread.properties.additionalInfo: '{{parsed_event.message.additionalInfo}}'
          azuread.properties.tokenIssuerType: '{{parsed_event.message.tokenIssuerType}}'
          azuread.properties.resourceTenantId: '{{parsed_event.message.resourceTenantId}}'
          azuread.properties.homeTenantId: '{{parsed_event.message.homeTenantId}}'
          azuread.properties.userType: '{{parsed_event.message.userType}}'
          azuread.properties.crossTenantAccessType: '{{parsed_event.message.crossTenantAccessType}}'
        filter: "{{azuread.properties != null}}"

      - set:
          action.target: "user"
        filter: "{{parsed_event.message.userId != null}}"

      - set:
          source.ip: "{{parsed_event.message.callerIpAddress}}"
          azuread.callerIpAddress: '{{parsed_event.message.callerIpAddress}}'
        filter: "{{parsed_event.message.callerIpAddress != '<null>' and parsed_event.message.callerIpAddress != null }}"

  log_type_auditlogs_has_message_properties:
    actions:
      - set:
          action.outcome_reason: "{{parsed_event.message.properties.resultReason}}"
          event.reason: "{{parsed_event.message.properties.resultReason}}"
        filter: "{{parsed_event.message.properties.result == 'failure'}}"
      - set:
          user.id: '{{ parsed_event.message.properties.initiatedBy.user.id}}'
          user.name: '{{ parsed_event.message.properties.initiatedBy.user.userPrincipalName}}'
          action.target: "user"
        filter: "{{parsed_event.message.properties.initiatedBy.user != null}}"

      - set:
          user.id: '{{ parsed_event.message.properties.initiatedBy.app.servicePrincipalId}}'
          user.name: '{{ parsed_event.message.properties.initiatedBy.app.displayName}}'
          action.target: "user"
        filter: "{{parsed_event.message.properties.initiatedBy.app != null}}"

  log_type_auditlogs:
    actions:
      - set:
          action.properties: >
            [
            {% for targetResource in parsed_event.message.properties.targetResources %}
            {% if targetResource.modifiedProperties != null %}
            {% for modifiedProperty in targetResource.modifiedProperties %}
            {% if modifiedProperty.displayName != "Included Updated Properties"%}
            {'name': '{{modifiedProperty.displayName or Null}}', 'newValue': '{{modifiedProperty.newValue or Null}}', 'oldValue': '{{modifiedProperty.oldValue or ""}}'},
            {% endif %}
            {% endfor %}
            {% endif %}
            {% if targetResource.type == "User" %}
            {'name': '{{targetResource.userPrincipalName | lower }}', 'id': '{{targetResource.id}}', 'type': 'targetedUser'},
            {% endif %}
            {% endfor %}
            ]
        filter: '{{parsed_event.message.properties.targetResources != [] }}'

      - set:
          action.properties: [ ]
        filter: '{{ parsed_event.message.properties.targetResources == [] }}'

  log_type_authentication:
    actions:
      - set:
          action.name: "authentication"
          event.category: "authentication"
          event.type: [ "start" ]