name: trend-micro-vision-one-oat
ignored_values: []
pipeline:
  - name: parsed_event
    external:
      name: json.parse-json
      properties:
        input_field: "{{original.message}}"
        output_field: message

  - name: set_ecs_fields

stages:
  set_ecs_fields:
    actions:
      - set:
          event.category: ["intrusion_detection"]
          event.type: ["info"]
          observer.vendor: "TrendMicro"
          observer.product: "Vision One"

      - set:
          "@timestamp": "{{parsed_event.message.detectedDateTime | to_rfc3339}}"

          host.name: "{{parsed_event.message.endpoint.endpointName}}"
          host.ip: "{{parsed_event.message.endpoint.ips}}"

          agent.id: "{{parsed_event.message.endpoint.agentGuid}}"
          event.start: "{{parsed_event.message.detail.firstSeen | to_rfc3339}}"
          event.end: "{{parsed_event.message.detail.lastSeen | to_rfc3339}}"

          host.id: "{{parsed_event.message.detail.endpointGuid}}"
          host.os.name: "{{parsed_event.message.detail.osName}}"
          host.os.version: "{{parsed_event.message.detail.osVer}}"
          host.os.full: "{{parsed_event.message.detail.osDescription}}"

          process.name: "{{parsed_event.message.detail.processName or parsed_event.message.detail.ObjectName}}"
          process.parent.pid: "{{parsed_event.message.detail.processPid}}"
          process.parent.user.name: "{{parsed_event.message.detail.processUser}}"
          process.parent.user.domain: "{{parsed_event.message.detail.processUserDomain}}"
          process.parent.start: "{{parsed_event.message.detail.processLaunchTime | to_rfc3339}}"
          process.parent.command_line: "{{parsed_event.message.detail.processCmd}}"
          process.parent.executable: "{{parsed_event.message.detail.processFilePath}}"
          process.parent.hash.sha1: "{{parsed_event.message.detail.processFileHashSha1}}"
          process.parent.hash.sha256: "{{parsed_event.message.detail.processFileHashSha256}}"
          process.parent.hash.md5: "{{parsed_event.message.detail.processFileHashMd5}}"
          process.parent.parent.name: "{{parsed_event.message.detail.parentName}}"
          process.parent.parent.executable: "{{parsed_event.message.detail.parentFilePath}}"
          process.parent.parent.command_line: "{{parsed_event.message.detail.parentCmd}}"
          process.parent.parent.pid: "{{parsed_event.message.detail.parentPid}}"
          process.parent.parent.start: "{{parsed_event.message.detail.parentLaunchTime | to_rfc3339}}"
          process.parent.parent.hash.sha1: "{{parsed_event.message.detail.parentFileHashSha1}}"
          process.parent.parent.hash.sha256: "{{parsed_event.message.detail.parentFileHashSha256}}"
          process.parent.parent.hash.md5: "{{parsed_event.message.detail.parentFileHashMd5}}"
          process.parent.parent.user.name: "{{parsed_event.message.detail.parentUser}}"
          process.parent.parent.user.domain: "{{parsed_event.message.detail.parentUserDomain}}"

          group.id: "{{parsed_event.message.detail.groupId}}"
          action.properties.ScriptBlockText: "{{parsed_event.message.detail.objectRawDataStr}}"

          user.name: "{{parsed_event.message.detail.objectUser}}"
          user.domain: "{{parsed_event.message.detail.objectUserDomain}}"

          process.pid: "{{parsed_event.message.detail.objectPid}}"
          process.command_line: "{{parsed_event.message.detail.objectCmd}}"
          process.executable: "{{parsed_event.message.detail.ObjectFilePath}}"
          process.hash.md5: "{{parsed_event.message.detail.ObjectFileHashMd5}}"
          process.hash.sha1: "{{parsed_event.message.detail.ObjectFileHashSha1}}"
          process.hash.sha256: "{{parsed_event.message.detail.ObjectFileHashSha256}}"

          threat.tactic.id: "{{parsed_event.message.filters | map(attribute='mitreTacticIds') | list | sum(start = [])}}"
          threat.technique.id: >
            [
            {%- for subtechnique_id in parsed_event.message.filters | map(attribute='mitreTechniqueIds') | list | sum(start = []) -%}
              {%- if "." not in subtechnique_id -%}'{{ subtechnique_id }}',{%- endif -%}
            {%- endfor -%}
            ]

          threat.technique.subtechnique.id: >
            [
            {%- for subtechnique_id in parsed_event.message.filters | map(attribute='mitreTechniqueIds') | list | sum(start = []) -%}
              {%- if "." in subtechnique_id -%}'{{ subtechnique_id }}',{%- endif -%}
            {%- endfor -%}
            ]
