name: trend-micro-vision-one-oat
ignored_values: []
pipeline:
  - name: parsed_event
    external:
      name: json.parse-json
      properties:
        input_field: "{{original.message}}"
        output_field: message

  - name: set_ecs_fields

stages:
  set_ecs_fields:
    actions:
      - set:
          event.kind: alert
          event.category: ["intrusion_detection"]
          event.type: ["info"]
          observer.vendor: "TrendMicro"
          observer.product: "Vision One"

      - set:
          "@timestamp": "{{parsed_event.message.detectedDateTime}}"

          host.name: "{{parsed_event.message.endpoint.endpointName}}"
          host.ip: "{{parsed_event.message.endpoint.ips}}"

          agent.id: "{{parsed_event.message.endpoint.agentGuid}}"
          event.start: "{{parsed_event.message.details.firstSeen}}"
          event.end: "{{parsed_event.message.details.lastSeen}}"

          host.id: "{{parsed_event.message.details.endpointGuid}}"
          host.os.name: "{{parsed_event.message.details.osName}}"
          host.os.version: "{{parsed_event.message.details.osVer}}"
          host.os.full: "{{parsed_event.message.details.osDescription}}"

          process.name: "{{parsed_event.message.details.processName or parsed_event.message.details.ObjectName}}"
          process.parent.pid: "{{parsed_event.message.details.processPid}}"
          process.parent.user.name: "{{parsed_event.message.details.processUser}}"
          process.parent.user.domain: "{{parsed_event.message.details.processUserDomain}}"
          process.parent.start: "{{parsed_event.message.details.processLaunchTime}}"
          process.parent.command_line: "{{parsed_event.message.details.processCmd}}"
          process.parent.executable: "{{parsed_event.message.details.processFilePath}}"
          process.parent.hash.sha1: "{{parsed_event.message.details.processFileHashSha1}}"
          process.parent.hash.sha256: "{{parsed_event.message.details.processFileHashSha256}}"
          process.parent.hash.md5: "{{parsed_event.message.details.processFileHashMd5}}"
          process.parent.parent.name: "{{parsed_event.message.details.parentName}}"
          process.parent.parent.executable: "{{parsed_event.message.details.parentFilePath}}"
          process.parent.parent.command_line: "{{parsed_event.message.details.parentCmd}}"
          process.parent.parent.pid: "{{parsed_event.message.details.parentPid}}"
          process.parent.parent.start: "{{parsed_event.message.details.parentLaunchTime}}"
          process.parent.parent.hash.sha1: "{{parsed_event.message.details.parentFileHashSha1}}"
          process.parent.parent.hash.sha256: "{{parsed_event.message.details.parentFileHashSha256}}"
          process.parent.parent.hash.md5: "{{parsed_event.message.details.parentFileHashMd5}}"
          process.parent.parent.user.name: "{{parsed_event.message.details.parentUser}}"
          process.parent.parent.user.domain: "{{parsed_event.message.details.parentUserDomain}}"

          group.id: "{{parsed_event.message.details.groupId}}"
          action.properties.ScriptBlockText: "{{parsed_event.message.details.objectRawDataStr}}"

          user.name: "{{parsed_event.message.details.objectUser}}"
          user.domain: "{{parsed_event.message.details.objectUserDomain}}"

          process.pid: "{{parsed_event.message.details.objectPid}}"
          process.command_line: "{{parsed_event.message.details.objectCmd}}"
          process.executable: "{{parsed_event.message.details.ObjectFilePath}}"
          process.hash.md5: "{{parsed_event.message.details.ObjectFileHashMd5}}"
          process.hash.sha1: "{{parsed_event.message.details.ObjectFileHashSha1}}"
          process.hash.sha256: "{{parsed_event.message.details.ObjectFileHashSha256}}"

          threat.tactic.id: "{{parsed_event.message.filters | map(attribute='mitreTacticIds') | list | sum(start = [])}}"
          threat.technique.id: "{{parsed_event.message.filters | map(attribute='mitreTechniqueIds') | list | sum(start = [])}}"
