name: Jizo
pipeline:
  - name: json_event
    description: ""
    filter: ""
    external:
      name: json.parse-json
      properties:
        input_field: "{{original.message}}"
        output_field: message

  - name: parsed_date
    description: ""
    filter: ""
    external:
      name: date.parse
      properties:
        input_field: "{{json_event.message.timestamp}}"
        output_field: datetime
        format: null
        timezone: UTC

  - name: set_base_fields

stages:
  set_base_fields:
    actions:
      - set:
          source.ip: "{{json_event.message.src_ip}}"
          "@timestamp": "{{json_event.message.timestamp}}"
          destination.ip: "{{json_event.message.dest_ip}}"
          destination.port: "{{json_event.message.dest_port}}"
          source.port: "{{json_event.message.src_port}}"
          network.protocol: "{{json_event.message.app_proto}}"
          network.transport: "{{json_load.message.proto}}"
          action.name: "{{json_event.message.alert.action}}"
          action.type: "{{json_event.message.event_type}}"
          action.properties.signature: "{{json_event.message.alert.signature}}"
          action.properties.category: "{{json_event.message.alert.category}}"
          action.properties.signature_id: "{{json_event.message.alert.signature_id}}"
          action.properties.severity: "{{json_event.message.alert.metadata.signature_severity[0]}}"
          event.severity: "{{json_event.message.alert.severity}}" 
          source.bytes: "{{json_event.message.flow.bytes_toserver}}"
          source.packets: "{{json_load.message.flow.pkts_toserver}}"
          destination.bytes: "{{json_load.message.flow.bytes_toclient}}"
          destination.packets: "{{json_load.message.flow.pkts_toclient}}"
          event.start: "{{json_event.message.flow.start}}"
          event.category: ["network"]
          event.type: ["connection"]

   

 

    
