name: ibm_i
pipeline:
  - name: parsed_event
    external:
      name: cef.parse-cef

  - name: set_common_fields

stages:
  set_common_fields:
    actions:
      - set:
          observer.vendor: "IBM"

      - set:
          event.category: ["process"]
          event.type: ["end"]
        filter: "{{parsed_event.message.reason in ['CPF1164', 'CPC1126', 'CPF0927']}}"

      - set:
          event.category: [ "process" ]
          event.type: [ "start" ]
        filter: "{{parsed_event.message.reason in ['CPF1124', 'Command string audit']}}"

      - set:
          event.category: [ "session" ]
          event.type: [ "start" ]
        filter: "{{parsed_event.message.reason in ['CPI3E34']}}"

      - set:
          event.category: [ "network" ]
          event.type: [ "end" ]
        filter: "{{parsed_event.message.reason in ['TCP2617']}}"

      - set:
          event.category: [ "authentication" ]
          event.type: [ "info" ]
        filter: "{{parsed_event.message.reason in ['Authority failure']}}"
