name: Check Data Leaks

on: [pull_request]

defaults:
  run:
    working-directory: .

jobs:
  scan-data-leaks:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: detect-secrets
        run : |
          pip install detect-secrets
          detect-secrets scan .
