name: Validate Yaml Files Format

on: [pull_request]

defaults:
  run:
    working-directory: .

jobs:
  validate-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Yamllint
        run: |
          yamllint -d "{extends: relaxed, rules: {line-length: {max: 199}}}" --no-warnings .
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
