name: Check intakes

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Run the action # You would run your tests before this using the output to set state/desc
        uses: Sibz/github-status-action@v1
        with: 
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: 'Check intakes'
          description: 'Waiting for status'
          state: 'pending'
          sha: ${{github.event.pull_request.head.sha || github.sha}}
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.JENKINS_SEKOIA_IO }}
          repository: SekoiaLab/platform
          event-type: edited-intakes
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.event.pull_request.head.sha || github.sha }}"}'   
